[package]
name = "crab-rave"
version = "0.1.0"
edition = "2024"

[lib]
name = "one_million_crabs"
path = "src/lib.rs"

[dependencies]
common-game = { git = "https://github.com/unitn-ap-2025/common.git" }
crossbeam-channel = "0.5.15"
env_logger = "0.11.8"
flexi_logger = "0.31.7"
log = "0.4"